version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      XTyPo2VwY/0kRWTIPFUxQytOhEQX+y02muGktaRu/ap60VPnMi8fdlpiARPzMt7QrFpjWFaGZqOuV3yqYwl20W2fXgENez0QIzH71lsOCBalA6h1xK6lUgOidzjIcno7f9uI14IxWmxdjbzNW7MQ6d7YhDoTPpIp8ucAXmWKYw3GAJEjNMoc6j/tFO1B1sVE7c89SfoZCsgO1P722L0JNvh3flzxhwjVuOA6QSxlsNsuTT+IxuJQ/DyCVerCTOAw0sCVImIJDKeqgUR256kBHasodpmTJmE1j0/1COcpwtp4uhTQnS8NuNeCWe5GEc2GxnctPN9q0FeUZJm9iCtQ9lsPE6v/xMWBo2DMWLM/lbpoTkPJJ3jUGbg/l1cuAQUbFRUtehYeHekUYKn8wFzOhDi26mgS4b57Bwcj6AoVE6YFCrH0zeFW4TCyzDQE4351mYLWyrIOtco3mp37kDJrQ9RRTbEcSsXUq518VA74xYYpIFdry5FLK9CneYCWM6HZzv+AZz+EppVFbRFIO90TOhMdUIM/FkFsF3PO9EQY3k++QNODwGnd3uTo9V5+qHoY/12Fza9As9E57A3PfIP9X2QxOjYVg7iv2tLZkS9GkrfX2yZBWVOZxFz8hxf34as2rUOrHYMJRC/4uQID49VWY+Vak2oqlwHCVTAn45rzFFc=
