version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      ha/xzo2MtWJ+m1ZgzQBa2Qph2gNrhRy0dTEsyUtnRn/6OjXcKFaY+hNlVFLC3vHFAHOBaMr6idiD6KQubL4s58FXqpARROUdzfs9S11wDwJqWkvfMhjn+wliJ3bSQ8Aa+GtnS/pSykWLm1zEp2LT1BFmaPcarMKaD1D9QgZ+2Us3uXeJY0Ldi/Qq+hh6XeE6uIsO6u+ZWwVy30uT0tunSMblVTGKxCCIQX8WXWpWzH7z5fPdWnwkB8Lr/hAPHDiAtq6U2EyjSlnSMe7Zn9LkYjlWfiIe7jHIGEKWq8CFaL1nCrIWSZ9+sCer7P1dAtWeZRd9q/Qln5HDuA4efyqpxhHJmnkLxKdpcI6JwS2Cdva6UoVQQLBBkfpfzZcDocY52WbyCwQ9mTwpgcKMr/8qCYz5HStNodHPLetouhjlhf4n7GeD4WI+8q78i5FSqgGLGq79LA/DtD5np+Y4hu8tQCsqd3AAW3Y5zs0sJ2gsqsvrS0LONO1YEIoj1Lpb0WH7m+GHsdRmob+QgmrYf8kXgFMZJyul40+hxU7zUfInkT+Ao7jbrXbuVfEF30s34dvjHBZPg7uHXhCVwG1sKXDfgxSIrkEMvJG/zcwojN5HN5gSPphDgY+du3YutgZDm487nPgXoZf06F2dn0W+Mkv1RZEcYs31qYnxv4Ctbk/whkU=
